version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm rebuild --update-binary # rebuild compiled pkgs without messing with yarn.lock
      - make server
      # node_modules are checked in, so that bits tested locally are same used in test,staging and production
      - npm prune --production #remove devDependencies to shrink filesize
      - cd node_modules && rm -rf typescript jest @types @jest @babel && cd ..
      - mkdir deploy
      - zip -r deploy/lambda.zip dist/ node_modules > /dev/null
      - ls -alh deploy/lambda.zip
      - 'sed -i "s|CodeUri: \./|CodeUri: deploy/lambda.zip|" aws/cloudformation/sam-template.yml'
      - aws cloudformation package --template-file aws/cloudformation/sam-template.yml --s3-bucket $DEPLOY_BUCKET --s3-prefix $DEPLOY_S3_PREFIX --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - sam-template.yml
    - outputtemplate.yaml
