AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Invoice PDF Service
  
Globals:
  Function:
    Timeout: 60
    Runtime: nodejs12.x
  
Resources:
  CreatePdfApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: jovisco-invoice-pdf-service
      StageName: Prod
      Cors:
        AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"


  CreatePdfFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/create-pdf/
      Handler: api.handler
      Policies:
        - AmazonS3FullAccess
        - AWSLambdaBasicExecutionRole
      Events:
        CreatePdf:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /create-pdf/{id}
            Method: post
            RestApiId:
              Ref: CreatePdfApi
